{
  config,
  pkgs,
  ...
}: {
  home.username = "voidy";
  home.homeDirectory = "/home/voidy";

  programs.mpv = {
    enable = true;
    config = {
      hwdec = "auto-safe";
      vo = "gpu";
      profile = "gpu-hq";
      gpu-context = "wayland";
      slang = "ar";
    };

    bindings = {
      "Ctrl+1" = "no-osd change-list glsl-shaders set \"~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl\"; show-text \"Anime4K: Mode A (HQ)\"";
      "Ctrl+2" = "no-osd change-list glsl-shaders set \"~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl\"; show-text \"Anime4K: Mode B (HQ)\"";
      "Ctrl+3" = "no-osd change-list glsl-shaders set \"~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl\"; show-text \"Anime4K: Mode C (HQ)\"";
      "Ctrl+4" = "no-osd change-list glsl-shaders set \"~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl\"; show-text \"Anime4K: Mode A+A (HQ)\"";
      "Ctrl+5" = "no-osd change-list glsl-shaders set \"~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl\"; show-text \"Anime4K: Mode B+B (HQ)\"";
      "Ctrl+6" = "no-osd change-list glsl-shaders set \"~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl\"; show-text \"Anime4K: Mode C+A (HQ)\"";
      "Ctrl+0" = "no-osd change-list glsl-shaders clr \"\"; show-text \"GLSL shaders cleared\"";
    };

    scripts = with pkgs; [
      mpvScripts.uosc
      mpvScripts.thumbfast
      mpvScripts.autosubsync-mpv
    ];
  };

  programs.git = {
    enable = true;
    userName = "VoidyWay";
    userEmail = "175210480+voidyway@users.noreply.github.com";

    extraConfig = {
      init.defaultBranch = "main";
      commit.gpgsign = true;
      tag.gpgSign = true;
      user.signingkey = "F26C70195A724EE6";
    };
  };

  programs.mangohud = {
    enable = true;
    settings = {
      # Config Generated by MangoJuice
      legacy_layout = false;
      pci_dev = "0000:03:00.0"; # AMD/ATI Navi 22 Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT rev c5
      gpu_stats = true;
      vram = true;
      gpu_core_clock = true;
      gpu_mem_clock = true;
      gpu_temp = true;
      gpu_mem_temp = true;
      gpu_power = true;
      throttling_status = true;
      cpu_stats = true;
      cpu_mhz = true;
      cpu_power = true;
      ram = true;
      swap = true;
      fps = true;
      fps_metrics = "avg,0.01";
      gamemode = true;
      no_display = true;
      display_server = true;
      frame_timing = true;
      frame_timing_detailed = true;
      toggle_logging = "Shift_L+F2";
      toggle_hud_position = "Shift_R+F11";
      fps_limit_method = "late";
      toggle_fps_limit = "Shift_L+F1";
      background_alpha = 0.5;
      position = "top-left";
      toggle_hud = "Shift_R+F12";
      gpu_color = "e01b24";
      cpu_color = "3584e4";
      fps_value = "30,60";
      fps_color = "cc0000,ffaa7f,92e79a";
      gpu_load_value = "60,90";
      gpu_load_color = "92e79a,ffaa7f,cc0000";
      cpu_load_value = "60,90";
      cpu_load_color = "92e79a,ffaa7f,cc0000";
      background_color = "000000";
      frametime_color = "00ff00";
      vram_color = "ad64c1";
      ram_color = "f6d32d";
      wine_color = "ff7800";
      engine_color = "ff7800";
      text_color = "ffffff";
    };
  };

  home.stateVersion = "25.05";
  programs.home-manager.enable = true;
}
